### PR TITLE
New character dommie

### PR DESCRIPTION
**Pull request by Neverlandse00**
Finished working on Washizuka Samurai character and split up animations for Golrio Aztec character

### CODE REVIEW

**Comment by digitalbrilliancehour** [comment]
@Capriangel  can you test again now? Characters have been cleaned up with correct animation names and updated models.txt. Both new characters should now be playable in game. They don't do damage yet, but hit boxes connect. Development team will handle attack values later.

**Review by digitalbrilliancehour — APPROVED** [review]
Characters now load in game according to QA.

**Comment by Capriangel** [comment]
Both characters are in the game. @digitalbrilliancehour thank you for fixing the bug.

**Comment by dhollingsworth2020** [comment]
What was the issue found? I see that something was fixed but am unsure of the original problem. There should have been a bug report added to the comment section of this pull request.

**Comment by digitalbrilliancehour** [comment]
I thought I actually posted the problem here, but I think it only went to @Capriangel . The problem was a few things:

 Characters have been cleaned up with correct animation names and updated models.txt. 

Animation names should always match what's listed here:
http://www.chronocrash.com/apps/wiki/obor/index.php?title=OpenBOR_Legacy_Manual#Animation_Types

And this is one thing I forgot to mention before, but when it comes to the number of attacks and specials one has, the "maxattacktypes" and "maxfreespecials" variables need to be updated to account for the number of attacks. The default value is 4, so I had to increase those(this is more of a development fix than design). One final thing is that the load method used in "Models.txt" for the players/characters always have to be set to "load". You would use "know" when loading anything else, like objects, enemies, .etc. Everything else was great, just those small tweaks that needed to happen. The load method "load" would then allow you to be able to select the characters and see how they play in the game. And had to get rid of the animations that we weren't going to use as they weren't deleted yet.  

Hope this helps.

**Pull request merged**
